services:
    app:
        container_name: Demo-SpringBoot-app
        hostname: app
        image: demo/springboot/app
        build:
            context: .
        ports:
            - "${APP_PORT:-80}:8080"
        networks:
            - app
        restart: always

networks:
    app:
        name: Demo-SpringBoot-app

version: "3.7"
