services:
    app:
        container_name: Demo-SpringBoot-app
        hostname: app
        image: demo/springboot/app
        build:
            context: .
        environment:
            DB_HOSTNAME: "${DB_HOSTNAME:-locahost}"
            DB_PORT: "${DB_PORT:-3306}"
            DB_DATABASE: "${DB_DATABASE:-app}"
            DB_USER: "${DB_USER:-app}"
            DB_PASS: "${DB_PASS:-app}"
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-STORAGENOTACCESSKEY}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-STORAGENOTSECRETKEY}
            AWS_PROFILE: ${AWS_PROFILE:-default}
            AWS_REGION: ${AWS_REGION:-us-east-2}
        ports:
            - "${APP_PORT:-80}:8080"
        networks:
            - app
        restart: always

networks:
    app:
        name: Demo-SpringBoot-app

version: "3.7"
